### PR TITLE
Add vignette Rmds (created from Rnws)

### PR DESCRIPTION
**Pull request by angela-li**
Thought I'd go ahead and start a PR for this. Things I'm going to add to this PR before it's ready to merge (this is an incomplete PR):

- Fix citations (need to add .bib files for each Rmd). I can produce these quickly in Zotero, but maybe @rsbivand you already have the citations, in any of these [file formats](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#specifying_a_bibliography)?
- Fix figure references
- Figure out what's going on with not being able to load data from `etc/backstore/*.RData` in `CO69.Rmd`, line 518 and `SpatialFiltering.Rmd`, line 90

And then we'll have a nice set of `Rmd`-ify-ed vignettes to include on the pkgdown site!

### CODE REVIEW

**Comment by rsbivand** [comment]
The etc/backstore is from the installed package, so if the vignette builder does not install spdep first, it will not find the file(s). The bib file is added to https://github.com/r-spatial/spdep/issues/25.

**Comment by angela-li** [comment]
Thanks for the comprehensive .bib file! All the vignettes have citations now, including the Anselin CD one (I didn't end up putting in DOIs for them though). 

I'm going to go through the Rmds again and fix any formatting issues, then will mark this PR as ready for your review.

**Comment by rsbivand** [comment]
The error message is: 

```
Error in tools::buildVignettes(dir = ".", tangle = TRUE) : 
  Detected vignette source files (‘CO69.Rmd’, ‘CO69.Rnw’, ‘sids.Rmd’, ‘sids.Rnw’, ‘SpatialFiltering.Rmd’, ‘SpatialFiltering.Rnw’) with shared names (‘CO69’, ‘sids’, ‘SpatialFiltering’) and therefore risking overwriting each others output files
Execution halted
```
so we'll have to do some odd stuff on master and temporarily rename the old *.Rnw files to unblock your PR. I'll try to do this to see if it works.

**Comment by rsbivand** [comment]
Looks good, need a further correction to remove:

```
* checking CRAN incoming feasibility ... NOTE
Maintainer: ‘Roger Bivand <Roger.Bivand@nhh.no>’

Found the following (possibly) invalid URLs:
  URL: http://sal.agecon.uiuc.edu/datasets/sids.zip
    From: inst/doc/sids.html
    Status: Error
    Message: libcurl error code 6:
      	Could not resolve host: sal.agecon.uiuc.edu
```
that would be the current GeoDa location of the actual file.

**Comment by rsbivand** [comment]
Also seeing:

```
Reading 'vignettes/SpatialFiltering.Rmd'
Writing 'articles/SpatialFiltering.html'
|WARNING] Note with key '1' defined at line 131 column 1 but not used.
```

on re-building the site.

**Comment by rsbivand** [comment]
Up on https://r-spatial.github.io/spdep/, now for some proof-reading?

**Pull request merged**
