### PR TITLE
Add package documentation website

### PR DESCRIPTION
**Pull request by angela-li**
I ran `pkgdown::build_site()` to generate the `docs` folder, which produces the package documentation website with Github Pages. I didn't convert the 2 Rnw files to Rmd, so those 2 vignettes don't build in pkgdown, but I can try my hand at that if you'd like.

### CODE REVIEW

**Comment by rsbivand** [comment]
I guess you would have to edit the file excluding docs from the R CMD build process, to prevent the proper R build train getting clogged up by the website, if this goes forward. I always build and check locally before committing and pushing, so its presence may be a problem in itself. I see that `sf` has a lot in the `.Rbuildignore` file.

**Comment by angela-li** [comment]
Great point. I updated `.Rbuildignore` so that docs are excluded from the R CMD build process.

**Comment by rsbivand** [comment]
Thanks, merged. I really appreciate your willingness to engage - lets see how this goes.

**Comment by rsbivand** [comment]
Do you know how to expose docs/index.html as a web page - though `README.md` - @edzer should it appear anywhere? Is the r-spatial.github.io/spdep location suitable, or rather as suggested above?

**Comment by angela-li** [comment]
You have to change the repository settings I believe. Check out the Github guide on how to publish from `docs` [here](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch).

**Comment by edzer** [comment]
Settings tab on the top of this page -> GitHub pages -> Source: select "master branch /docs folder". And then it appears at  r-spatial.github.io/spdep, sometimes a minute later.

**Comment by rsbivand** [comment]
Which is the theme used by **sf**?

**Comment by rsbivand** [comment]
I added @angela-li to DESCRIPTION. Will `docs/authors.html` update automatically?

**Comment by edzer** [comment]
It does after you run `devtools::build_site()` in the spdep directory, verify by browsing docs/index.html, and on success commit & push the docs directory.

**Comment by rsbivand** [comment]
Help!:

```
Building the package will delete...
  '/home/rsb/topics/packages/github/spdep/inst/doc'
Are you sure?

1: Yes
2: No
```

I have valuable content in inst/doc - stored simulation objects used in an Rnw vignette.

Why is RS/TV so dictatorial?

**Comment by edzer** [comment]
No clue. Move its contents somewhere else?

**Comment by rsbivand** [comment]
Moved to inst/etc, I'll see what the dictator stuffs in inst/doc. If it is /docs, I will tear it out and revert to no pkgdown, of course.

**Comment by rsbivand** [comment]
This message with no explanation.

```
Error in replayPlot(x) : invalid graphics state
```
Does `devtools::build_site()` require that this is done in RS? If so, I will not use it.

**Comment by rsbivand** [comment]
Further, vignettes/nb_igraph.Rmd comes up with UNKOWN TITLE, then flips to its title. A big mess, really not worth the trouble. Examples are to be run, not looked at!!!

**Comment by edzer** [comment]
I see the replayPlot error too in Rstudio, and no articles (vignettes). @angela-li which setup did you use to generate the docs?

**Comment by rsbivand** [comment]
Same replayPlot in RS. No idea where it comes from. Committing and pushing, will raise issue for someone else to sort out - I do not have the time or patience to adapt to RS/DS etc.

**Comment by rsbivand** [comment]
Wow - this pkgdown rubbish has peppered /src with `*.o` and `spdep.so`, presumably because it builds in-tree and only cleans later. It also put 

```
	docs/docsearch.js
	docs/reference/nboperations-2.png
	docs/reference/nboperations-3.png
```

in the package tree. What a mess! Issue possibly in or after `docs/reference/residuals.sarlm.html` as subsequent files not in commit list.

**Comment by rsbivand** [comment]
And the real disaster - the examples in reference pages omit `\dontrun` examples, which must be displayed without exception!!! All `\donttest` should be shown but not run (it seems to try to run them and fails), all `\dontrun` should be shown. I put a lot of time into exposing the corner cases in the examples, together with user comments accumulated over twenty years. The must be exposed. If pkgdown is not accommodating, it is not fit for purpose.

**Comment by rsbivand** [comment]
Resolved by editing example to reduce plot margins.

**Comment by rsbivand** [comment]
The `authors.html` link was visible in the preview, but is no longer visible form `index.html`. I give up ...

**Comment by rsbivand** [comment]
The `authors.html` link was visible in the preview, but is no longer visible form `index.html`. I give up ...

**Pull request merged**
