### PR TITLE
implement local bivariate moran

### PR DESCRIPTION
**Pull request by JosiahParry**
This pull request creates an implementation of the bivariate local moran.

It creates: 

- `local-moran-bv.R` which implements the local bivariate moran
  - note that it uses folded conditional permutation approach to calculating the pseudo p-value
- `utils-cond-permute.R` which provides helper functions to implement conditional permutation of a listw object

`devtools::check()` returns 0 errors, 0 warnings, and 2 notes. 

```
── R CMD check results ──────────────────────────────────────── spdep 1.2-6 ────
Duration: 2m 5.1s

❯ checking package dependencies ... NOTE
  Packages suggested but not available for checking: 'spatialreg', 'RSpectra'

❯ checking installed package size ... NOTE
    installed size is  9.3Mb
    sub-directories of 1Mb or more:
      doc   6.7Mb
      etc   1.4Mb

0 errors ✔ | 0 warnings ✔ | 2 notes ✖

R CMD check succeeded
```

### CODE REVIEW

**Comment by JosiahParry** [comment]
Sounds good! 
To confirm, by derivation you mean the paper?

**Comment by rsbivand** [comment]
Yes, if there is a published paper or something that has a stable link like a DOI -  web pages do disappear over time, leaving us without an "authority".

**Comment by JosiahParry** [comment]
The Local BV Moran is discussed in section 3.2 of [this proceedings paper](http://europa.nvc.cs.vt.edu/~ctlu/Project/SoftwareTools/multi_lisa.pdf). The citation has been updated. The paper uses the columbus dataset. I've compared to rgeoda and the results are _almost_ identical. The difference, I think, is due to rounding error between R and the C++ implementation in rgeoda. The below comparisons of the values that do not match. The match up to the 10th decimal place. The difference exists past that it seems.


``` r
devtools::load_all()
library(sf)
library(rgeoda)

columbus <- st_read(system.file("shapes/columbus.shp", package="spData"))

nb <- poly2nb(columbus)
listw <- nb2listw(nb)
lmss <- localmoran_bv(columbus$CRIME, columbus$INC, listw)

queen_w <- queen_weights(columbus)
lisa <- local_bimoran(queen_w, columbus[c("CRIME", "INC")])
lms <- lisa_values(lisa)

# some are not matching
not_matching <- which(lmss$Ib != lms)

cbind(lmss$Ib[not_matching], lms[not_matching])
#>                [,1]          [,2]
#>  [1,] -1.2368494456 -1.2368494456
#>  [2,] -1.2010054212 -1.2010054212
#>  [3,] -0.9879712511 -0.9879712511
#>  [4,] -0.6057303757 -0.6057303757
#>  [5,] -0.0006014046 -0.0006014046
#>  [6,] -0.0068813684 -0.0068813684
#>  [7,] -0.8788967496 -0.8788967496
#>  [8,] -0.1256865340 -0.1256865340
#>  [9,] -0.5510119267 -0.5510119267
#> [10,]  0.1181174820  0.1181174820
#> [11,] -0.9901007017 -0.9901007017
#> [12,] -1.2709838927 -1.2709838927
#> [13,] -1.3940681427 -1.3940681427
#> [14,]  0.0761664412  0.0761664412
#> [15,] -0.0560342555 -0.0560342555
#> [16,]  0.0094888641  0.0094888641

# compare the two results

rg_nbs <- lapply(0:(nrow(columbus)-1), 
                 \(.x) sort(queen_w$GetNeighbors(.x) + 1))

all(lengths(rg_nbs) == card(nb))
#> [1] TRUE
all.equal(nb, rg_nbs,
          check.attributes = FALSE,
          use.names = FALSE)
#> [1] TRUE

# perhaps the lags of y are different
diff_lags <- rgeoda::spatial_lag(queen_w, columbus[c("INC")])[,1] -
  lag.listw(listw, columbus$INC)

diff_lags[which(abs(diff_lags) > 0)]
#>  [1]  1.776357e-15 -1.776357e-15  3.552714e-15  1.776357e-15 -1.776357e-15
#>  [6]  1.776357e-15  3.552714e-15  1.776357e-15 -1.776357e-15  3.552714e-15
#> [11]  1.776357e-15  3.552714e-15 -3.552714e-15  1.776357e-15 -1.776357e-15
```

<sup>Created on 2022-09-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by JosiahParry** [comment]
@rsbivand, the branch has been updated with proper citation and columbus example. Please let me know of any further actions required.

**Comment by JosiahParry** [comment]
Wonderful! Thanks :)

**Pull request merged**
